# Generated by Django 5.1 on 2024-08-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
    ]
