# Generated by Django 5.1 on 2024-08-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_autor_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
            ],
        ),
    ]
